### ISSUE TITLE
Bro how to fix it on Kali 

### ISSUE THREAD

**Issue by ibrahimomartm1** [dragonked2/Egysql#1]
python egysql.py
Traceback (most recent call last):
  File "/home/kali/Desktop/Github/dragonked2/Egysql/egysql.py", line 286, in <module>
    curses.wrapper(main)
  File "/usr/lib/python3.11/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/Github/dragonked2/Egysql/egysql.py", line 227, in main
    stdscr.addstr(7 + i, 0, line, curses.color_pair(2))
_curses.error: addwstr() returned ERR

**Comment by dragonked2** [comment]
fixed download latest version
